### ISSUE TITLE
Space Problem 

### ISSUE THREAD

**Issue by Ninetailz** [Ninetailz/novel#2]
The lines are too long for one paragraph, they are long one line text instead of paragraph

**Comment by gurkirat12** [comment]
so you want me to like write shorter lines about 15 words per line.

**Comment by Ninetailz** [comment]
Yea I suggest that too but if you select word warp it will be in one paragraph but when you submit it, it goes back to the pervious problem. So I think we should just cut the lines for now?

**Comment by gurkirat12** [comment]
yes that would be the best option for now i suppose. anyway it will be fixed in the word so we should just cut the lines.

**Comment by Ninetailz** [comment]
Ok, then either me or you will fix it by cutting lines 
#bugresolved#
